github: 
  is_project_page: false
theme: jekyll-theme-hacker
title: Ngan Ji Cheng
description: Welcome to my about me page! I am a Year 2 Information Security student in the National University of Singapore (NUS). I am expecting to graduate in 2022 with a Bachelor of Computing in Information Security (with Honours).

github: 
  is_project_page: false
theme: jekyll-theme-minimal
title: Ryan Y.W. Tan
description: A current undergraduate at the National University of Singapore.
