theme: jekyll-theme-minimal
title: Ryan Yi Wei Tan
logo: https://github.com/RyanTanYiWei/ryantanyiwei.github.io/blob/main/selfpic2.JPG?raw=true
description: Graduate Student at Technische Universiteit Delft